# Root configuration file for ESLint
root: true

# Environment settings
env:
  browser: true # Enables browser global variables
  es2020: true # Enables ES2020 syntax

# Extends recommended ESLint configurations
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react-hooks/recommended

# Files and directories to ignore
ignorePatterns:
  - dist # Ignore the dist directory
  - vite.config.ts

# Specify the parser
parser: "@typescript-eslint/parser"

# Parser options
parserOptions:
  project: "./tsconfig.eslint.json"

# ESLint plugins to use
plugins:
  - react-refresh

# Custom ESLint rules
rules:
  react-refresh/only-export-components:
    - warn
    - allowConstantExport: true # Allow constant exports

  # General Best Practices
  eqeqeq: error # Require the use of === and !== for comparison
  no-implicit-coercion: error # Disallow shorthand type conversions (e.g., !!value)
  consistent-return: error # Require return statements to either always or never specify values

  # Stylistic Issues
  semi: error # Require semicolons at the end of statements
  quotes:
    - error
    - "double" # Enforce the consistent use of double quotes
  indent:
    - error
    - tab # Enforce indentation with tabs
    - SwitchCase: 1
